### ISSUE TITLE
Forwarding multiple ports to the container failed

### ISSUE THREAD

**Issue by sdqinhao** [truenas/charts#1]
```
midclt call -job chart.release.create '{"catalog": "OFFICIAL", "train": "test", "item": "ix-chart", "values": {"image": {"repository": "linuxserver/qbittorrent"}, "portFor
wardingList": [{"containerPort": 16831, "nodePort": 16831, "protocol": "UDP"},{"containerPort": 9080, "nodePort": 9080}],"containerEnvironmentVariables": [{"name": "PUID", "value":
 "1000"}, {"name": "PGID", "value": "1000"}, {"name": "TZ", "value": "Asia/Shanghai"}, {"name": "UMASK_SET", "value": "022"}, {"name": "WEBUI_PORT", "value": "9080"}], "volumes": [
 {"datasetName": "config", "mountPath": "/config"}],"hostPathVolumes": [{"hostPath": "/mnt/JBOD/Media", "mountPath": "/Media","readOnly": false }, {"hostPath": "/mnt/JBOD/Download"
, "mountPath": "/downloads","readOnly": false }], "workloadType": "Deployment"}, "version": "2010.0.1", "release_name": "qbittorrent"}'
Status: Installing Catalog Item
Total Progress: [##############################__________] 75.00%
[EFAULT] Failed to install catalog item: b'Error: Service "qbittorrent-ix-chart" is invalid: [spec.ports[0].name: Required value, spec.ports[1].name: Required value]\n'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 372, in run
    await self.future
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 408, in __run_body
    rv = await self.method(*([self] + args))
  File "/usr/lib/python3/dist-packages/middlewared/schema.py", line 1022, in nf
    return await f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/middlewared/plugins/chart_releases_linux/chart_release.py", line 223, in do_create
    raise CallError(f'Failed to install catalog item: {cp.stderr}')
middlewared.service_exception.CallError: [EFAULT] Failed to install catalog item: b'Error: Service "qbittorrent-ix-chart" is invalid: [spec.ports[0].name: Required value, spec.ports[1].name: Required value]\n'
```

**Comment by sonicaj** [comment]
Thank you @sdqinhao for reporting this, please use the version `2010.0.2` for deploying your workload.
