### ISSUE TITLE
Immich: upgrade 1.85.0_1.0.35 -> 1.87.0_1.1.0 #1773

### ISSUE THREAD

**Issue by umarkashmiri** [truenas/charts#1778]
While attempting to upgrade, I encounter the following error. 

Error: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 426, in run
    await self.future
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 464, in __run_body
    rv = await self.method(*([self] + args))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/schema/processor.py", line 177, in nf
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/schema/processor.py", line 44, in nf
    res = await f(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/plugins/chart_releases_linux/upgrade.py", line 115, in upgrade
    await self.upgrade_chart_release(job, release, options)
  File "/usr/lib/python3/dist-packages/middlewared/plugins/chart_releases_linux/upgrade.py", line 265, in upgrade_chart_release
    config, context = await self.middleware.call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1398, in call
    return await self._call(
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1341, in _call
    return await methodobj(*prepared_call.args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/plugins/chart_releases_linux/chart_release.py", line 339, in normalise_and_validate_values
    dict_obj = await self.middleware.call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1398, in call
    return await self._call(
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1341, in _call
    return await methodobj(*prepared_call.args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/plugins/chart_releases_linux/validation.py", line 53, in validate_values
    verrors.check()
  File "/usr/lib/python3/dist-packages/middlewared/service_exception.py", line 70, in check
    raise self
middlewared.service_exception.ValidationErrors: [EINVAL] values.immichStorage.library.hostPathConfig.hostPath: attribute required
[EINVAL] values.immichStorage.pgBackup.hostPathConfig.hostPath: attribute required
[EINVAL] values.immichStorage.pgData.hostPathConfig.hostPath: attribute required
[EINVAL] values.immichStorage.profile.hostPathConfig.hostPath: attribute required
[EINVAL] values.immichStorage.thumbs.hostPathConfig.hostPath: attribute required
[EINVAL] values.immichStorage.uploads.hostPathConfig.hostPath: attribute required
[EINVAL] values.immichStorage.video.hostPathConfig.hostPath: attribute required

**Comment by dani162** [comment]
There is a 1.88.1 version. Installing this version worked for me, maybe try to refresh your charts.
Discover Apps -> Refresh Charts
on Cobia
![image](https://github.com/truenas/charts/assets/34603476/700f030e-3008-4ed7-86b8-9dee589045ac)

**Comment by stavros-k** [comment]
> While attempting to upgrade, I encounter the following error.

Which version to which version please?

**Comment by iXPert12** [comment]
I can confirm that the update to 1.88.1 works, but the hostpath issue still persists in config(edit app).

![image](https://github.com/truenas/charts/assets/2253764/81bf01a3-4da8-46f8-9d04-963d9238682e)

Also I've checked other apps, this also happens to qbittorrent and filebrowser.

**Comment by stavros-k** [comment]
> Edit: this happens on Bluefin 22.12.4.2

Can you please upgrade to Cobia and let me know?

Note that the type and path will be immutable still.
But it should show the hostPath there.

**Comment by umarkashmiri** [comment]
I am using Cobia TrueNAS-SCALE-23.10.0.1
upgrading to 1.88.2_2.0.1 from 1.85.0_1.0.35 is working for me now.
@stavros-k yes in cobia it is showing path in disabled state for all the apps.
