### ISSUE TITLE
Plex 2.0.1 Chart Upgrade Fails

### ISSUE THREAD

**Issue by timothystewart6** [truenas/charts#2126]
Hi, when trying to upgrade to `2.0.1`

It fails with:

`[EFAULT] Failed to upgrade App: Persistence - Expected to start with a forward slash [/]`

```

More info...
 Error: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 427, in run
    await self.future
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 465, in __run_body
    rv = await self.method(*([self] + args))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/schema/processor.py", line 177, in nf
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/schema/processor.py", line 44, in nf
    res = await f(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/plugins/chart_releases_linux/upgrade.py", line 115, in upgrade
    await self.upgrade_chart_release(job, release, options)
  File "/usr/lib/python3/dist-packages/middlewared/plugins/chart_releases_linux/upgrade.py", line 299, in upgrade_chart_release
    await self.middleware.call('chart.release.helm_action', release_name, chart_path, config, 'upgrade')
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1399, in call
    return await self._call(
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1353, in _call
    return await self.run_in_executor(prepared_call.executor, methodobj, *prepared_call.args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1251, in run_in_executor
    return await loop.run_in_executor(pool, functools.partial(method, *args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/plugins/chart_releases_linux/helm.py", line 49, in helm_action
    raise CallError(f'Failed to {tn_action} App: {errmsg}')
middlewared.service_exception.CallError: [EFAULT] Failed to upgrade App: Persistence - Expected <mountPath> to start with a forward slash [/]
```

All o f my mount paths start with a forward slash, everything works fine with `1.7.60`

**Comment by stavros-k** [comment]
Hey! Would you mind sharing your app configuration please? (mainly the storage section) 

Either the output of the following command or a screenshot

```
# replace `plex` with the name you gave to the app
midclt call chart.release.get_instance "plex" | jq '.config'`
```

Remember to hide any secrets (eg claim token)

Thanks!

**Comment by timothystewart6** [comment]
Thank you!  This was my fault (I think?)

```json
    {
      "hostPath": "/mnt/storage0/recorded_tv",
      "mountPath": "recorded_tv",
      "readOnly": false
    }
```

I changed in the web ui, now I can upgrade


```json
    {
      "hostPath": "/mnt/storage0/recorded_tv",
      "mountPath": "/recorded_tv",
      "readOnly": false
    }
```

This is really odd, I don't remember setting a mount point without a proceeding `/`.

Also, if this is required for upgrades, why not validate this in the form when creating the app?

Also, thank you very much for helping!

**Comment by stavros-k** [comment]
To be honest I wasn't aware that k8s accept paths without proceeding `/`. 
With this migration, there is a lot more validation in place! 
Tho, not in the form, **yet!**.

At the moment it only shows the "friendlier" message you saw 
eg 
```
[EFAULT] Failed to upgrade App: Persistence - Expected to start with a forward slash [/]
```

If there isn't any other issue, should we close this?

**Comment by timothystewart6** [comment]
I agree, not sure how that happened, if it were me or a bug somewhere along the way.  Sure, you can close this.  Thank you so much!
