### ISSUE TITLE
Unable to migrate to latest version of photoprism

### ISSUE THREAD

**Issue by ESteanes** [truenas/charts#2312]
Hi, I tried upgrading to the latest version of photo prism but am running into an issue where it is erroring out:
```
 Error: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 426, in run
    await self.future
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 461, in __run_body
    rv = await self.method(*([self] + args))
  File "/usr/lib/python3/dist-packages/middlewared/schema.py", line 1318, in nf
    return await func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/middlewared/schema.py", line 1186, in nf
    res = await f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/middlewared/plugins/chart_releases_linux/upgrade.py", line 115, in upgrade
    await self.upgrade_chart_release(job, release, options)
  File "/usr/lib/python3/dist-packages/middlewared/plugins/chart_releases_linux/upgrade.py", line 252, in upgrade_chart_release
    config = await self.middleware.call('chart.release.upgrade_values', release, catalog_item['location'])
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1386, in call
    return await self._call(
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1346, in _call
    return await self.run_in_executor(prepared_call.executor, methodobj, *prepared_call.args)
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1249, in run_in_executor
    return await loop.run_in_executor(pool, functools.partial(method, *args, **kwargs))
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/middlewared/plugins/chart_releases_linux/upgrade.py", line 320, in upgrade_values
    raise CallError(f'Failed to apply migration: {stderr.decode()}')
middlewared.service_exception.CallError: [EFAULT] Failed to apply migration: Traceback (most recent call last):
  File "<path>/catalogs/github_com_truenas_charts_git_master/charts/photoprism/2.0.4/migrations/migrate", line 98, in <module>
    print(json.dumps(migrate(json.loads(f.read()))))
  File "<path>/catalogs/github_com_truenas_charts_git_master/charts/photoprism/2.0.4/migrations/migrate", line 89, in migrate
    return migrate_common_lib(values)
  File "<path>/catalogs/github_com_truenas_charts_git_master/charts/photoprism/2.0.4/migrations/migrate", line 32, in migrate_common_lib
    'hostNetwork': values['host_network'],
KeyError: 'host_network'
```
https://github.com/truenas/charts/blob/50c51f5fcd66c5237387a7c17b9d4f7509858ffc/charts/photoprism/2.0.4/migrations/migrate#L32

Given it links back to this line https://github.com/truenas/charts/blob/50c51f5fcd66c5237387a7c17b9d4f7509858ffc/charts/photoprism/2.0.4/migrations/migrate#L92 it seems like the migrate file is being called incorrectly.

**Comment by stavros-k** [comment]
Hello, from which version are you trying to upgrade?
Can you share output of the following command?

```
midclt call chart.release.query photoprism | jq '.config.'
```
Change `photoprism` with the name you gave to the app (if its different)
Also remember to hide sensitive info, if any.

Thanks

**Comment by ESteanes** [comment]
Just to clarify, this is running from Truenas' shell, not the Pod Shell.
This is the output:
```
root@truenas[~]# midclt call chart.release.query photoprism
[EINVAL] query-filters: Not a list
```
Current version of photoprism: `221118_1.0.19`
Upgrade version of photoprism: `231128_2.0.4`

Truenas version: TrueNAS-SCALE-22.12.2

I understand I'm on a bit of an older version of Truenas - would upgrading make a difference?

**Comment by stavros-k** [comment]
Please upgrade to `23.10` for TrueNAS SCALE, give it enough time to redeploy all your apps.
Might take some time in case there are images that might need to be re-donwloaded.

Then upgrade photprism to `1.1.3`
And then upgrade photoprism to `2.0.0`

This should work fine!

Let me know if you have any issues.
Thanks!

**Comment by ESteanes** [comment]
Ok yeah I think the trick was doing the intermediate upgrade. Interestingly I could never get `1.1.3` to start up properly as it wasn't able to download the pod image.
```
 2024-03-28 8:58:27
Failed to pull image "photoprism/photoprism:231128": rpc error: code = Unknown desc = context deadline exceeded
2024-03-28 8:58:27
Error: ErrImagePull
2024-03-28 8:58:27
Error: ImagePullBackOff
2024-03-28 8:58:27
Back-off pulling image "photoprism/photoprism:231128"
2024-03-28 8:56:28
Add eth0 [172.16.0.8/16] from ix-net
2024-03-28 8:56:28
Pulling image "photoprism/photoprism:231128"
```
