### ISSUE TITLE
[home-assistant] - zeroconf error when "Host Network" is ticked on

### ISSUE THREAD

**Issue by tannisroot** [truenas/charts#2385]
If you install the Home Assistant chart and keep all of the options default except for "Host Network", Home Assistant will complain in the Notifications on each startup that it can't set up Zeroconf.
Turning off the "Host Network" solves this, however, this prevents Home Assistant from discovering devices on the network (at least in my situation). I was hoping that if I enabled the option, Home Assistant would be able to auto-discover devices on the network, which is quite essential for its functionality.
I should mention that I do have a bridge set up in TrueNAS, and I was able to get an IP assigned to a container just fine with a chart from TrueCharts (ESPHome), although the option for that there is a bit different.
Let me know if I you need any additional information or more detailed reproduction steps.
```2024-04-16 09:57:10.173265+03:00s6-rc: info: service s6rc-oneshot-runner: starting
2024-04-16 09:57:10.174484+03:00s6-rc: info: service s6rc-oneshot-runner successfully started
2024-04-16 09:57:10.174536+03:00s6-rc: info: service fix-attrs: starting
2024-04-16 09:57:10.176330+03:00s6-rc: info: service fix-attrs successfully started
2024-04-16 09:57:10.176362+03:00s6-rc: info: service legacy-cont-init: starting
2024-04-16 09:57:10.177979+03:00s6-rc: info: service legacy-cont-init successfully started
2024-04-16 09:57:10.178020+03:00s6-rc: info: service legacy-services: starting
2024-04-16 09:57:10.180505+03:00services-up: info: copying legacy longrun home-assistant (no readiness notification)
2024-04-16 09:57:10.233914+03:00s6-rc: info: service legacy-services successfully started
2024-04-16 09:57:12.600648+03:00[31m2024-04-16 09:57:12.596 ERROR (MainThread) [homeassistant.setup] Error during setup of component zeroconf
2024-04-16 09:57:12.600701+03:00Traceback (most recent call last):
2024-04-16 09:57:12.600711+03:00File "/usr/src/homeassistant/homeassistant/setup.py", line 398, in _async_setup_component
2024-04-16 09:57:12.600720+03:00result = await task
2024-04-16 09:57:12.600728+03:00^^^^^^^^^^
2024-04-16 09:57:12.600736+03:00File "/usr/src/homeassistant/homeassistant/components/zeroconf/__init__.py", line 224, in async_setup
2024-04-16 09:57:12.600750+03:00aio_zc = await _async_get_instance(hass, **zc_args)
2024-04-16 09:57:12.600759+03:00^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-16 09:57:12.600767+03:00File "/usr/src/homeassistant/homeassistant/components/zeroconf/__init__.py", line 161, in _async_get_instance
2024-04-16 09:57:12.600775+03:00zeroconf = HaZeroconf(**zcargs)
2024-04-16 09:57:12.600783+03:00^^^^^^^^^^^^^^^^^^^^
2024-04-16 09:57:12.600797+03:00File "/usr/local/lib/python3.12/site-packages/zeroconf/_core.py", line 180, in __init__
2024-04-16 09:57:12.600805+03:00listen_socket, respond_sockets = create_sockets(interfaces, unicast, ip_version, apple_p2p=apple_p2p)
2024-04-16 09:57:12.600813+03:00^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-16 09:57:12.600822+03:00File "/usr/local/lib/python3.12/site-packages/zeroconf/_utils/net.py", line 358, in create_sockets
2024-04-16 09:57:12.600835+03:00listen_socket = new_socket(ip_version=ip_version, apple_p2p=apple_p2p, bind_addr=('',))
2024-04-16 09:57:12.600843+03:00^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-16 09:57:12.600851+03:00File "/usr/local/lib/python3.12/site-packages/zeroconf/_utils/net.py", line 248, in new_socket
2024-04-16 09:57:12.600864+03:00s.bind(bind_tup)
2024-04-16 09:57:12.600872+03:00OSError: [Errno 98] Address in use[0m
2024-04-16 09:57:12.702729+03:00[33m2024-04-16 09:57:12.701 WARNING (SyncWorker_6) [py.warnings] /usr/local/lib/python3.12/site-packages/pyudev/monitor.py:137: SyntaxWarning: invalid escape sequence '\ '
2024-04-16 09:57:12.702766+03:00"""
2024-04-16 09:57:12.702776+03:00[0m
2024-04-16 09:57:13.652651+03:00[31m2024-04-16 09:57:13.652 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of 'default_config'. Setup failed for dependencies: ['zeroconf'][0m
2024-04-16 09:57:13.652846+03:00[31m2024-04-16 09:57:13.652 ERROR (MainThread) [homeassistant.setup] Setup failed for 'default_config': Could not setup dependencies: zeroconf[0m```

**Comment by stavros-k** [comment]
If i'm not wrong this is because it conflicts with the host's mDNS.
You have to disable one of the two.

**Comment by tannisroot** [comment]
> If i'm not wrong this is because it conflicts with the host's mDNS. You have to disable one of the two.

Indeed, disabling it got rid of the issue. For some reason I assumed using "Host Networking" would be like assigining a dedicated network interface to it, like with a Truechart, with the container getting its own IP on the network. My bad.
