### ISSUE TITLE
Nextcloud update Fails nginx.externalAccessPort: Should be between 443 and 65535

### ISSUE THREAD

**Issue by jwilleke** [truenas/charts#2451]
Truenas Dragonfish-24.04.0
No idea what this implies as I have not control over the NGINX pod embedded in NextCloud.

Only port I have to set is the 20810 which is what the default value.

More info...
```
 Error: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 469, in run
    await self.future
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 511, in __run_body
    rv = await self.method(*args)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/schema/processor.py", line 187, in nf
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/schema/processor.py", line 47, in nf
    res = await f(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/plugins/chart_releases_linux/upgrade.py", line 116, in upgrade
    await self.upgrade_chart_release(job, release, options)
  File "/usr/lib/python3/dist-packages/middlewared/plugins/chart_releases_linux/upgrade.py", line 267, in upgrade_chart_release
    config, context = await self.middleware.call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1564, in call
    return await self._call(
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1417, in _call
    return await methodobj(*prepared_call.args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/plugins/chart_releases_linux/chart_release.py", line 352, in normalise_and_validate_values
    dict_obj = await self.middleware.call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1564, in call
    return await self._call(
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1417, in _call
    return await methodobj(*prepared_call.args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/plugins/chart_releases_linux/validation.py", line 54, in validate_values
    verrors.check()
  File "/usr/lib/python3/dist-packages/middlewared/service_exception.py", line 70, in check
    raise self
middlewared.service_exception.ValidationErrors: [EINVAL] values.ncNetwork.nginx.externalAccessPort: Should be between 443 and 65535
```

**Comment by stavros-k** [comment]
Hello,
Can you clarify from which nextcloud version did you upgrade and to which version?
Thanks

**Comment by jwilleke** [comment]
Name: nextcloud
App Version: 29.0.0_2.0.2
Chart Version: 2.0.2

Trying to go to 
App Version: 29.0.0_2.0.3

When I originally set this up, I had no certificate used and then changed it use a certificate.
I edited it through template.

I see in the output of:

```
midclt call chart.release.get_instance nextcloud | jq '.config'
...
  "ncNetwork": {
    "certificateID": 12,
    "nginx": {
      "externalAccessPort": 80,
      "proxyTimeouts": 120,
      "useDifferentAccessPort": false
    },
    "webPort": 20810
```

Seems on of the issues with Truenas Scale is the dialogs so much from being set or changed.

**Comment by stavros-k** [comment]
Okay, can you refresh your catalog and upgrade to 2.0.4?

Make sure you also check the notes here after you upgrade, you might or might not need to do anything.
https://github.com/truenas/charts/pull/2447#issue-2285114348

**Comment by dukeside** [comment]
Same issue, refreshing the catalog and upgrading to 2.0.4 fixed it for me.

**Comment by jwilleke** [comment]
Truenas Dragonfish-24.04.0 

Clicking update at Application Info Panel
Current Nextcloud: 29.0.0_2.0.2 
Current Nextcloud: 29.0.0_2.0.4

> No nextcloud images running.

Dialog shows:
Images ( to be updated )
- There are no images requiring upgrade
Changelog
- No Changelog

So no idea if this is from the earlier attempt or not.

```  Error: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 469, in run
    await self.future
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 511, in __run_body
    rv = await self.method(*args)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/schema/processor.py", line 187, in nf
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/schema/processor.py", line 47, in nf
    res = await f(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/plugins/chart_releases_linux/upgrade.py", line 116, in upgrade
    await self.upgrade_chart_release(job, release, options)
  File "/usr/lib/python3/dist-packages/middlewared/plugins/chart_releases_linux/upgrade.py", line 267, in upgrade_chart_release
    config, context = await self.middleware.call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1564, in call
    return await self._call(
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1417, in _call
    return await methodobj(*prepared_call.args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/plugins/chart_releases_linux/chart_release.py", line 352, in normalise_and_validate_values
    dict_obj = await self.middleware.call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1564, in call
    return await self._call(
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1417, in _call
    return await methodobj(*prepared_call.args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/plugins/chart_releases_linux/validation.py", line 54, in validate_values
    verrors.check()
  File "/usr/lib/python3/dist-packages/middlewared/service_exception.py", line 70, in check
    raise self
middlewared.service_exception.ValidationErrors: [EINVAL] values.ncNetwork.nginx.externalAccessPort: Should be between 443 and 65535
```

**Comment by stavros-k** [comment]
@jwilleke 
Please do the following,

- Edit the nextcloud application in TrueNAS webui.
- Click save without any changes.
- (It should save without errors)
- Now try the upgrade again.

Let me know if that works
Thanks

**Comment by jwilleke** [comment]
No differences Observed.

Still showed
There are no images requiring upgrade

I also have this issue with Nextcloud which I was hopping would be fixed by upgrading. I switched from non-secure to secure port.

2024-05-10 04:17:57.129572-04:00[Fri May 10 08:17:57.129476 2024] [php:notice] [pid 174] [client 172.16.0.1:59470] Nextcloud trustedProxies has malformed entries


``` bash
 Error: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 469, in run
    await self.future
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 511, in __run_body
    rv = await self.method(*args)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/schema/processor.py", line 187, in nf
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/schema/processor.py", line 47, in nf
    res = await f(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/plugins/chart_releases_linux/upgrade.py", line 116, in upgrade
    await self.upgrade_chart_release(job, release, options)
  File "/usr/lib/python3/dist-packages/middlewared/plugins/chart_releases_linux/upgrade.py", line 267, in upgrade_chart_release
    config, context = await self.middleware.call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1564, in call
    return await self._call(
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1417, in _call
    return await methodobj(*prepared_call.args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/plugins/chart_releases_linux/chart_release.py", line 352, in normalise_and_validate_values
    dict_obj = await self.middleware.call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1564, in call
    return await self._call(
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1417, in _call
    return await methodobj(*prepared_call.args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/plugins/chart_releases_linux/validation.py", line 54, in validate_values
    verrors.check()
  File "/usr/lib/python3/dist-packages/middlewared/service_exception.py", line 70, in check
    raise self
middlewared.service_exception.ValidationErrors: [EINVAL] values.ncNetwork.nginx.externalAccessPort: Should be between 443 and 65535

```

**Comment by stavros-k** [comment]
Do you have selected a certificate for nextcloud?

**Comment by jwilleke** [comment]
First, really appreciate the help. I know it hard to deal with "Humans".  Code is much easier. 

Yes. I have a certificate from internal CA.

I installed NextCloud to test to see if it would meet my needs to get off Google.

I did not when I first deployed nextcloud.
When I installed the Nextcloud "Memories" Nextcloud wanted collabora installed, I used the trueNAS chart, and somewhere complained about not secure.

So I added a certificate.

When I launch Nexcloud from the Applications Screen

"You are trying to open:
http://192.168.68.122:20810
Because HTTP to HTTPS redirect is enabled in settings your browser will force HTTPS connection for this URL.
This may create issues if app does not support secure connections."

Browser redirects to:

<https://192.168.68.122/apps/dashboard/> Looses port

Expected it to be:
<https://192.168.68.122:20810/apps/dashboard/>

**Comment by stavros-k** [comment]
Okay!

Edit the app and Check the "use different port"
Enter the port you access the instance
It should look something like this

![image](https://github.com/truenas/charts/assets/47820033/921cc04a-9166-4ea5-9294-ae8904af5cc1)

**Comment by jwilleke** [comment]
That appears to have worked.
Thanks!

**Comment by stavros-k** [comment]
Awesome thanks for letting me know!
