### ISSUE TITLE
Audiobookself failing to load large number of podcasts

### ISSUE THREAD

**Issue by joeySchentrup** [truenas/charts#2517]
When I attempt to download a large number of podcasts (~400), the app freezes and crashes. It does not seem to have to do with the exact podcasts I am downloading as the cap is cross podcasts. This means if I have 350 episodes in one podcast, I cannot download more that 50 in another one I want to add. I am using the "Add" button in the sidebar of the podcast library to add the podcasts to the server and downloading them using the search icon in the podcast.

This does not seem to be an issue with audiobookshelf itself as the only [reference](https://www.truenas.com/community/threads/audiobookshelf-is-crashing-in-truenas-scale-socket-disconnected-socket-failed-to-connect.117562/) I can find to this error I am having comes from another person using this on TrueNAS. The error content is posted below. 

After the app crashes, it restarts and comes back but I can no longer delete episodes or add new ones. Doing so crashes the app again. I am only able to recover by deleting a podcast from my library and them downloading less items. 

Error Log:
```
FATAL

[Server] Unhandled rejection: SequelizeDatabaseError: SQLITE_IOERR: disk I/O error, promise: Promise { <rejected> Error at Database.<anonymous> (/node_modules/sequelize/lib/dialects/sqlite/query.js:185:27) at /node_modules/sequelize/lib/dialects/sqlite/query.js:183:50 at new Promise (<anonymous>) at Query.run (/node_modules/sequelize/lib/dialects/sqlite/query.js:183:12) at /node_modules/sequelize/lib/sequelize.js:315:28 at async SQLiteQueryInterface.select (/node_modules/sequelize/lib/dialects/abstract/query-interface.js:407:12) at async libraryItem.findAll (/node_modules/sequelize/lib/model.js:1140:21) at async libraryItem.findOne (/node_modules/sequelize/lib/model.js:1240:12) at async libraryItem.findByPk (/node_modules/sequelize/lib/model.js:1221:12) at async libraryItem.fullUpdateFromOld (/server/models/LibraryItem.js:239:33) { name: 'SequelizeDatabaseError', parent: [Error: SQLITE_IOERR: disk I/O error] { errno: 10, code: 'SQLITE_IOERR', sql: "SELECT `libraryItem`.`id`, `libraryItem`.`ino`, `libraryItem`.`path`, `libraryItem`.`relPath`, `libraryItem`.`mediaId`, `libraryItem`.`mediaType`, `libraryItem`.`isFile`, `libraryItem`.`isMissing`, `libraryItem`.`isInvalid`, `libraryItem`.`mtime`, `libraryItem`.`ctime`, `libraryItem`.`birthtime`, `libraryItem`.`size`, `libraryItem`.`lastScan`, `libraryItem`.`lastScanVersion`, `libraryItem`.`libraryFiles`, `libraryItem`.`extraData`, `libraryItem`.`createdAt`, `libraryItem`.`updatedAt`, `libraryItem`.`libraryId`, `libraryItem`.`libraryFolderId`, `book`.`id` AS `book.id`, `book`.`title` AS `book.title`, `book`.`titleIgnorePrefix` AS `book.titleIgnorePrefix`, `book`.`subtitle` AS `book.subtitle`, `book`.`publishedYear` AS `book.publishedYear`, `book`.`publishedDate` AS `book.publishedDate`, `book`.`publisher` AS `book.publisher`, `book`.`description` AS `book.description`, `book`.`isbn` AS `book.isbn`, `book`.`asin` AS `book.asin`, `book`.`language` AS `book.language`, `book`.`explicit` AS `book.explicit`, `book`.`abridged` AS `book.abridged`, `book`.`coverPath` AS `book.coverPath`, `book`.`duration` AS `book.duration`, `book`.`narrators` AS `book.narrators`, `book`.`audioFiles` AS `book.audioFiles`, `book`.`ebookFile` AS `book.ebookFile`, `book`.`chapters` AS `book.chapters`, `book`.`tags` AS `book.tags`, `book`.`genres` AS `book.genres`, `book`.`createdAt` AS `book.createdAt`, `book`.`updatedAt` AS `book.updatedAt`, `book->authors`.`id` AS `book.authors.id`, `book->authors`.`name` AS `book.authors.name`, `book->authors`.`lastFirst` AS `book.authors.lastFirst`, `book->authors`.`asin` AS `book.authors.asin`, `book->authors`.`description` AS `book.authors.description`, `book->authors`.`imagePath` AS `book.authors.imagePath`, `book->authors`.`createdAt` AS `book.authors.createdAt`, `book->authors`.`updatedAt` AS `book.authors.updatedAt`, `book->authors`.`libraryId` AS `book.authors.libraryId`, `book->series`.`id` AS `book.series.id`, `book->series`.`name` AS `book.series.name`, `book->series`.`nameIgnorePrefix` AS `book.series.nameIgnorePrefix`, `book->series`.`description` AS `book.series.description`, `book->series`.`createdAt` AS `book.series.createdAt`, `book->series`.`updatedAt` AS `book.series.updatedAt`, `book->series`.`libraryId` AS `book.series.libraryId`, `book->series->bookSeries`.`id` AS `book.series.bookSeries.id`, `book->series->bookSeries`.`sequence` AS `book.series.bookSeries.sequence`, `podcast`.`id` AS `podcast.id`, `podcast`.`title` AS `podcast.title`, `podcast`.`titleIgnorePrefix` AS `podcast.titleIgnorePrefix`, `podcast`.`author` AS `podcast.author`, `podcast`.`releaseDate` AS `podcast.releaseDate`, `podcast`.`feedURL` AS `podcast.feedURL`, `podcast`.`imageURL` AS `podcast.imageURL`, `podcast`.`description` AS `podcast.description`, `podcast`.`itunesPageURL` AS `podcast.itunesPageURL`, `podcast`.`itunesId` AS `podcast.itunesId`, `podcast`.`itunesArtistId` AS `podcast.itunesArtistId`, `podcast`.`language` AS `podcast.language`, `podcast`.`podcastType` AS `podcast.podcastType`, `podcast`.`explicit` AS `podcast.explicit`, `podcast`.`autoDownloadEpisodes` AS `podcast.autoDownloadEpisodes`, `podcast`.`autoDownloadSchedule` AS `podcast.autoDownloadSchedule`, `podcast`.`lastEpisodeCheck` AS `podcast.lastEpisodeCheck`, `podcast`.`maxEpisodesToKeep` AS `podcast.maxEpisodesToKeep`, `podcast`.`maxNewEpisodesToDownload` AS `podcast.maxNewEpisodesToDownload`, `podcast`.`coverPath` AS `podcast.coverPath`, `podcast`.`tags` AS `podcast.tags`, `podcast`.`genres` AS `podcast.genres`, `podcast`.`createdAt` AS `podcast.createdAt`, `podcast`.`updatedAt` AS `podcast.updatedAt`, `podcast->podcastEpisodes`.`id` AS `podcast.podcastEpisodes.id`, `podcast->podcastEpisodes`.`index` AS `podcast.podcastEpisodes.index`, `podcast->podcastEpisodes`.`season` AS `podcast.podcastEpisodes.season`, `podcast->podcastEpisodes`.`episode` AS `podcast.podcastEpisodes.episode`, `podcast->podcastEpisodes`.`episodeType` AS `podcast.podcastEpisodes.episodeType`, `podcast->podcastEpisodes`.`title` AS `podcast.podcastEpisodes.title`, `podcast->podcastEpisodes`.`subtitle` AS `podcast.podcastEpisodes.subtitle`, `podcast->podcastEpisodes`.`description` AS `podcast.podcastEpisodes.description`, `podcast->podcastEpisodes`.`pubDate` AS `podcast.podcastEpisodes.pubDate`, `podcast->podcastEpisodes`.`enclosureURL` AS `podcast.podcastEpisodes.enclosureURL`, `podcast->podcastEpisodes`.`enclosureSize` AS `podcast.podcastEpisodes.enclosureSize`, `podcast->podcastEpisodes`.`enclosureType` AS `podcast.podcastEpisodes.enclosureType`, `podcast->podcastEpisodes`.`publishedAt` AS `podcast.podcastEpisodes.publishedAt`, `podcast->podcastEpisodes`.`audioFile` AS `podcast.podcastEpisodes.audioFile`, `podcast->podcastEpisodes`.`chapters` AS `podcast.podcastEpisodes.chapters`, `podcast->podcastEpisodes`.`extraData` AS `podcast.podcastEpisodes.extraData`, `podcast->podcastEpisodes`.`createdAt` AS `podcast.podcastEpisodes.createdAt`, `podcast->podcastEpisodes`.`updatedAt` AS `podcast.podcastEpisodes.updatedAt`, `podcast->podcastEpisodes`.`podcastId` AS `podcast.podcastEpisodes.podcastId` FROM `libraryItems` AS `libraryItem` LEFT OUTER JOIN `books` AS `book` ON `libraryItem`.`mediaId` = `book`.`id` LEFT OUTER JOIN ( `bookAuthors` AS `book->authors->bookAuthor` INNER JOIN `authors` AS `book->authors` ON `book->authors`.`id` = `book->authors->bookAuthor`.`authorId`) ON `book`.`id` = `book->authors->bookAuthor`.`bookId` LEFT OUTER JOIN ( `bookSeries` AS `book->series->bookSeries` INNER JOIN `series` AS `book->series` ON `book->series`.`id` = `book->series->bookSeries`.`seriesId`) ON `book`.`id` = `book->series->bookSeries`.`bookId` LEFT OUTER JOIN `podcasts` AS `podcast` ON `libraryItem`.`mediaId` = `podcast`.`id` LEFT OUTER JOIN `podcastEpisodes` AS `podcast->podcastEpisodes` ON `podcast`.`id` = `podcast->podcastEpisodes`.`podcastId` WHERE `libraryItem`.`id` = '1bf0cd76-f36e-48d5-93f2-5fa36be3a815';" }, original: [Error: SQLITE_IOERR: disk I/O error] { errno: 10, code: 'SQLITE_IOERR', sql: "SELECT `libraryItem`.`id`, `libraryItem`.`ino`, `libraryItem`.`path`, `libraryItem`.`relPath`, `libraryItem`.`mediaId`, `libraryItem`.`mediaType`, `libraryItem`.`isFile`, `libraryItem`.`isMissing`, `libraryItem`.`isInvalid`, `libraryItem`.`mtime`, `libraryItem`.`ctime`, `libraryItem`.`birthtime`, `libraryItem`.`size`, `libraryItem`.`lastScan`, `libraryItem`.`lastScanVersion`, `libraryItem`.`libraryFiles`, `libraryItem`.`extraData`, `libraryItem`.`createdAt`, `libraryItem`.`updatedAt`, `libraryItem`.`libraryId`, `libraryItem`.`libraryFolderId`, `book`.`id` AS `book.id`, `book`.`title` AS `book.title`, `book`.`titleIgnorePrefix` AS `book.titleIgnorePrefix`, `book`.`subtitle` AS `book.subtitle`, `book`.`publishedYear` AS `book.publishedYear`, `book`.`publishedDate` AS `book.publishedDate`, `book`.`publisher` AS `book.publisher`, `book`.`description` AS `book.description`, `book`.`isbn` AS `book.isbn`, `book`.`asin` AS `book.asin`, `book`.`language` AS `book.language`, `book`.`explicit` AS `book.explicit`, `book`.`abridged` AS `book.abridged`, `book`.`coverPath` AS `book.coverPath`, `book`.`duration` AS `book.duration`, `book`.`narrators` AS `book.narrators`, `book`.`audioFiles` AS `book.audioFiles`, `book`.`ebookFile` AS `book.ebookFile`, `book`.`chapters` AS `book.chapters`, `book`.`tags` AS `book.tags`, `book`.`genres` AS `book.genres`, `book`.`createdAt` AS `book.createdAt`, `book`.`updatedAt` AS `book.updatedAt`, `book->authors`.`id` AS `book.authors.id`, `book->authors`.`name` AS `book.authors.name`, `book->authors`.`lastFirst` AS `book.authors.lastFirst`, `book->authors`.`asin` AS `book.authors.asin`, `book->authors`.`description` AS `book.authors.description`, `book->authors`.`imagePath` AS `book.authors.imagePath`, `book->authors`.`createdAt` AS `book.authors.createdAt`, `book->authors`.`updatedAt` AS `book.authors.updatedAt`, `book->authors`.`libraryId` AS `book.authors.libraryId`, `book->series`.`id` AS `book.series.id`, `book->series`.`name` AS `book.series.name`, `book->series`.`nameIgnorePrefix` AS `book.series.nameIgnorePrefix`, `book->series`.`description` AS `book.series.description`, `book->series`.`createdAt` AS `book.series.createdAt`, `book->series`.`updatedAt` AS `book.series.updatedAt`, `book->series`.`libraryId` AS `book.series.libraryId`, `book->series->bookSeries`.`id` AS `book.series.bookSeries.id`, `book->series->bookSeries`.`sequence` AS `book.series.bookSeries.sequence`, `podcast`.`id` AS `podcast.id`, `podcast`.`title` AS `podcast.title`, `podcast`.`titleIgnorePrefix` AS `podcast.titleIgnorePrefix`, `podcast`.`author` AS `podcast.author`, `podcast`.`releaseDate` AS `podcast.releaseDate`, `podcast`.`feedURL` AS `podcast.feedURL`, `podcast`.`imageURL` AS `podcast.imageURL`, `podcast`.`description` AS `podcast.description`, `podcast`.`itunesPageURL` AS `podcast.itunesPageURL`, `podcast`.`itunesId` AS `podcast.itunesId`, `podcast`.`itunesArtistId` AS `podcast.itunesArtistId`, `podcast`.`language` AS `podcast.language`, `podcast`.`podcastType` AS `podcast.podcastType`, `podcast`.`explicit` AS `podcast.explicit`, `podcast`.`autoDownloadEpisodes` AS `podcast.autoDownloadEpisodes`, `podcast`.`autoDownloadSchedule` AS `podcast.autoDownloadSchedule`, `podcast`.`lastEpisodeCheck` AS `podcast.lastEpisodeCheck`, `podcast`.`maxEpisodesToKeep` AS `podcast.maxEpisodesToKeep`, `podcast`.`maxNewEpisodesToDownload` AS `podcast.maxNewEpisodesToDownload`, `podcast`.`coverPath` AS `podcast.coverPath`, `podcast`.`tags` AS `podcast.tags`, `podcast`.`genres` AS `podcast.genres`, `podcast`.`createdAt` AS `podcast.createdAt`, `podcast`.`updatedAt` AS `podcast.updatedAt`, `podcast->podcastEpisodes`.`id` AS `podcast.podcastEpisodes.id`, `podcast->podcastEpisodes`.`index` AS `podcast.podcastEpisodes.index`, `podcast->podcastEpisodes`.`season` AS `podcast.podcastEpisodes.season`, `podcast->podcastEpisodes`.`episode` AS `podcast.podcastEpisodes.episode`, `podcast->podcastEpisodes`.`episodeType` AS `podcast.podcastEpisodes.episodeType`, `podcast->podcastEpisodes`.`title` AS `podcast.podcastEpisodes.title`, `podcast->podcastEpisodes`.`subtitle` AS `podcast.podcastEpisodes.subtitle`, `podcast->podcastEpisodes`.`description` AS `podcast.podcastEpisodes.description`, `podcast->podcastEpisodes`.`pubDate` AS `podcast.podcastEpisodes.pubDate`, `podcast->podcastEpisodes`.`enclosureURL` AS `podcast.podcastEpisodes.enclosureURL`, `podcast->podcastEpisodes`.`enclosureSize` AS `podcast.podcastEpisodes.enclosureSize`, `podcast->podcastEpisodes`.`enclosureType` AS `podcast.podcastEpisodes.enclosureType`, `podcast->podcastEpisodes`.`publishedAt` AS `podcast.podcastEpisodes.publishedAt`, `podcast->podcastEpisodes`.`audioFile` AS `podcast.podcastEpisodes.audioFile`, `podcast->podcastEpisodes`.`chapters` AS `podcast.podcastEpisodes.chapters`, `podcast->podcastEpisodes`.`extraData` AS `podcast.podcastEpisodes.extraData`, `podcast->podcastEpisodes`.`createdAt` AS `podcast.podcastEpisodes.createdAt`, `podcast->podcastEpisodes`.`updatedAt` AS `podcast.podcastEpisodes.updatedAt`, `podcast->podcastEpisodes`.`podcastId` AS `podcast.podcastEpisodes.podcastId` FROM `libraryItems` AS `libraryItem` LEFT OUTER JOIN `books` AS `book` ON `libraryItem`.`mediaId` = `book`.`id` LEFT OUTER JOIN ( `bookAuthors` AS `book->authors->bookAuthor` INNER JOIN `authors` AS `book->authors` ON `book->authors`.`id` = `book->authors->bookAuthor`.`authorId`) ON `book`.`id` = `book->authors->bookAuthor`.`bookId` LEFT OUTER JOIN ( `bookSeries` AS `book->series->bookSeries` INNER JOIN `series` AS `book->series` ON `book->series`.`id` = `book->series->bookSeries`.`seriesId`) ON `book`.`id` = `book->series->bookSeries`.`bookId` LEFT OUTER JOIN `podcasts` AS `podcast` ON `libraryItem`.`mediaId` = `podcast`.`id` LEFT OUTER JOIN `podcastEpisodes` AS `podcast->podcastEpisodes` ON `podcast`.`id` = `podcast->podcastEpisodes`.`podcastId` WHERE `libraryItem`.`id` = '1bf0cd76-f36e-48d5-93f2-5fa36be3a815';" }, sql: "SELECT `libraryItem`.`id`, `libraryItem`.`ino`, `libraryItem`.`path`, `libraryItem`.`relPath`, `libraryItem`.`mediaId`, `libraryItem`.`mediaType`, `libraryItem`.`isFile`, `libraryItem`.`isMissing`, `libraryItem`.`isInvalid`, `libraryItem`.`mtime`, `libraryItem`.`ctime`, `libraryItem`.`birthtime`, `libraryItem`.`size`, `libraryItem`.`lastScan`, `libraryItem`.`lastScanVersion`, `libraryItem`.`libraryFiles`, `libraryItem`.`extraData`, `libraryItem`.`createdAt`, `libraryItem`.`updatedAt`, `libraryItem`.`libraryId`, `libraryItem`.`libraryFolderId`, `book`.`id` AS `book.id`, `book`.`title` AS `book.title`, `book`.`titleIgnorePrefix` AS `book.titleIgnorePrefix`, `book`.`subtitle` AS `book.subtitle`, `book`.`publishedYear` AS `book.publishedYear`, `book`.`publishedDate` AS `book.publishedDate`, `book`.`publisher` AS `book.publisher`, `book`.`description` AS `book.description`, `book`.`isbn` AS `book.isbn`, `book`.`asin` AS `book.asin`, `book`.`language` AS `book.language`, `book`.`explicit` AS `book.explicit`, `book`.`abridged` AS `book.abridged`, `book`.`coverPath` AS `book.coverPath`, `book`.`duration` AS `book.duration`, `book`.`narrators` AS `book.narrators`, `book`.`audioFiles` AS `book.audioFiles`, `book`.`ebookFile` AS `book.ebookFile`, `book`.`chapters` AS `book.chapters`, `book`.`tags` AS `book.tags`, `book`.`genres` AS `book.genres`, `book`.`createdAt` AS `book.createdAt`, `book`.`updatedAt` AS `book.updatedAt`, `book->authors`.`id` AS `book.authors.id`, `book->authors`.`name` AS `book.authors.name`, `book->authors`.`lastFirst` AS `book.authors.lastFirst`, `book->authors`.`asin` AS `book.authors.asin`, `book->authors`.`description` AS `book.authors.description`, `book->authors`.`imagePath` AS `book.authors.imagePath`, `book->authors`.`createdAt` AS `book.authors.createdAt`, `book->authors`.`updatedAt` AS `book.authors.updatedAt`, `book->authors`.`libraryId` AS `book.authors.libraryId`, `book->series`.`id` AS `book.series.id`, `book->series`.`name` AS `book.series.name`, `book->series`.`nameIgnorePrefix` AS `book.series.nameIgnorePrefix`, `book->series`.`description` AS `book.series.description`, `book->series`.`createdAt` AS `book.series.createdAt`, `book->series`.`updatedAt` AS `book.series.updatedAt`, `book->series`.`libraryId` AS `book.series.libraryId`, `book->series->bookSeries`.`id` AS `book.series.bookSeries.id`, `book->series->bookSeries`.`sequence` AS `book.series.bookSeries.sequence`, `podcast`.`id` AS `podcast.id`, `podcast`.`title` AS `podcast.title`, `podcast`.`titleIgnorePrefix` AS `podcast.titleIgnorePrefix`, `podcast`.`author` AS `podcast.author`, `podcast`.`releaseDate` AS `podcast.releaseDate`, `podcast`.`feedURL` AS `podcast.feedURL`, `podcast`.`imageURL` AS `podcast.imageURL`, `podcast`.`description` AS `podcast.description`, `podcast`.`itunesPageURL` AS `podcast.itunesPageURL`, `podcast`.`itunesId` AS `podcast.itunesId`, `podcast`.`itunesArtistId` AS `podcast.itunesArtistId`, `podcast`.`language` AS `podcast.language`, `podcast`.`podcastType` AS `podcast.podcastType`, `podcast`.`explicit` AS `podcast.explicit`, `podcast`.`autoDownloadEpisodes` AS `podcast.autoDownloadEpisodes`, `podcast`.`autoDownloadSchedule` AS `podcast.autoDownloadSchedule`, `podcast`.`lastEpisodeCheck` AS `podcast.lastEpisodeCheck`, `podcast`.`maxEpisodesToKeep` AS `podcast.maxEpisodesToKeep`, `podcast`.`maxNewEpisodesToDownload` AS `podcast.maxNewEpisodesToDownload`, `podcast`.`coverPath` AS `podcast.coverPath`, `podcast`.`tags` AS `podcast.tags`, `podcast`.`genres` AS `podcast.genres`, `podcast`.`createdAt` AS `podcast.createdAt`, `podcast`.`updatedAt` AS `podcast.updatedAt`, `podcast->podcastEpisodes`.`id` AS `podcast.podcastEpisodes.id`, `podcast->podcastEpisodes`.`index` AS `podcast.podcastEpisodes.index`, `podcast->podcastEpisodes`.`season` AS `podcast.podcastEpisodes.season`, `podcast->podcastEpisodes`.`episode` AS `podcast.podcastEpisodes.episode`, `podcast->podcastEpisodes`.`episodeType` AS `podcast.podcastEpisodes.episodeType`, `podcast->podcastEpisodes`.`title` AS `podcast.podcastEpisodes.title`, `podcast->podcastEpisodes`.`subtitle` AS `podcast.podcastEpisodes.subtitle`, `podcast->podcastEpisodes`.`description` AS `podcast.podcastEpisodes.description`, `podcast->podcastEpisodes`.`pubDate` AS `podcast.podcastEpisodes.pubDate`, `podcast->podcastEpisodes`.`enclosureURL` AS `podcast.podcastEpisodes.enclosureURL`, `podcast->podcastEpisodes`.`enclosureSize` AS `podcast.podcastEpisodes.enclosureSize`, `podcast->podcastEpisodes`.`enclosureType` AS `podcast.podcastEpisodes.enclosureType`, `podcast->podcastEpisodes`.`publishedAt` AS `podcast.podcastEpisodes.publishedAt`, `podcast->podcastEpisodes`.`audioFile` AS `podcast.podcastEpisodes.audioFile`, `podcast->podcastEpisodes`.`chapters` AS `podcast.podcastEpisodes.chapters`, `podcast->podcastEpisodes`.`extraData` AS `podcast.podcastEpisodes.extraData`, `podcast->podcastEpisodes`.`createdAt` AS `podcast.podcastEpisodes.createdAt`, `podcast->podcastEpisodes`.`updatedAt` AS `podcast.podcastEpisodes.updatedAt`, `podcast->podcastEpisodes`.`podcastId` AS `podcast.podcastEpisodes.podcastId` FROM `libraryItems` AS `libraryItem` LEFT OUTER JOIN `books` AS `book` ON `libraryItem`.`mediaId` = `book`.`id` LEFT OUTER JOIN ( `bookAuthors` AS `book->authors->bookAuthor` INNER JOIN `authors` AS `book->authors` ON `book->authors`.`id` = `book->authors->bookAuthor`.`authorId`) ON `book`.`id` = `book->authors->bookAuthor`.`bookId` LEFT OUTER JOIN ( `bookSeries` AS `book->series->bookSeries` INNER JOIN `series` AS `book->series` ON `book->series`.`id` = `book->series->bookSeries`.`seriesId`) ON `book`.`id` = `book->series->bookSeries`.`bookId` LEFT OUTER JOIN `podcasts` AS `podcast` ON `libraryItem`.`mediaId` = `podcast`.`id` LEFT OUTER JOIN `podcastEpisodes` AS `podcast->podcastEpisodes` ON `podcast`.`id` = `podcast->podcastEpisodes`.`podcastId` WHERE `libraryItem`.`id` = '1bf0cd76-f36e-48d5-93f2-5fa36be3a815';", parameters: {} } }
```

**Comment by joeySchentrup** [comment]
@stavros-k That seemed to fix the issue! Thank you!
