### ISSUE TITLE
Frigate can not start. 

### ISSUE THREAD

**Issue by Danit2** [truenas/charts#2536]
When I try to start Frigate, I always get an error message: 
```Readinessprobe failed: Get "http://192.168.1.151:5000/api": dial tcp 192.168.1.151:5000: connect: connection refused ```

The first time the app starts, everything works without any problems. After that, it can no longer be started.

**Comment by stavros-k** [comment]
Please share the logs of the container. 

Thanks

**Comment by Danit2** [comment]
Good morning. 

After reading a lot of logs i have found the problem. 
My Coral TPU was not found. 
When i comment out the detector part of the config file frigate start as normal. 

But why it can happen that a missig TPU rest in a bootloop?


2024-06-05T08:45:59.177365596+02:00 s6-rc: info: service s6rc-fdholder: starting
2024-06-05T08:45:59.177458727+02:00 s6-rc: info: service s6rc-oneshot-runner: starting
2024-06-05T08:45:59.179322788+02:00 s6-rc: info: service s6rc-oneshot-runner successfully started
2024-06-05T08:45:59.179393404+02:00 s6-rc: info: service fix-attrs: starting
2024-06-05T08:45:59.180171918+02:00 s6-rc: info: service s6rc-fdholder successfully started
2024-06-05T08:45:59.182608823+02:00 s6-rc: info: service fix-attrs successfully started
2024-06-05T08:45:59.182680619+02:00 s6-rc: info: service legacy-cont-init: starting
2024-06-05T08:45:59.185865071+02:00 s6-rc: info: service legacy-cont-init successfully started
2024-06-05T08:45:59.185899973+02:00 s6-rc: info: service log-prepare: starting
2024-06-05T08:45:59.191566380+02:00 s6-rc: info: service log-prepare successfully started
2024-06-05T08:45:59.191648748+02:00 s6-rc: info: service nginx-log: starting
2024-06-05T08:45:59.191763785+02:00 s6-rc: info: service go2rtc-log: starting
2024-06-05T08:45:59.191860733+02:00 s6-rc: info: service frigate-log: starting
2024-06-05T08:45:59.192960515+02:00 s6-rc: info: service nginx-log successfully started
2024-06-05T08:45:59.193126855+02:00 s6-rc: info: service go2rtc-log successfully started
2024-06-05T08:45:59.193206147+02:00 s6-rc: info: service go2rtc: starting
2024-06-05T08:45:59.193380616+02:00 s6-rc: info: service frigate-log successfully started
2024-06-05T08:45:59.194491017+02:00 s6-rc: info: service go2rtc successfully started
2024-06-05T08:45:59.194592047+02:00 s6-rc: info: service go2rtc-healthcheck: starting
2024-06-05T08:45:59.194694089+02:00 s6-rc: info: service frigate: starting
2024-06-05T08:45:59.196100082+02:00 s6-rc: info: service go2rtc-healthcheck successfully started
2024-06-05T08:45:59.196282508+02:00 s6-rc: info: service frigate successfully started
2024-06-05T08:45:59.196375103+02:00 s6-rc: info: service nginx: starting
2024-06-05T08:45:59.198136479+02:00 s6-rc: info: service nginx successfully started
2024-06-05T08:45:59.198211893+02:00 s6-rc: info: service legacy-services: starting
2024-06-05T08:45:59.199406588+02:00 2024-06-05 06:45:59.199252272  [INFO] Preparing Frigate...
2024-06-05T08:45:59.200602038+02:00 2024-06-05 06:45:59.200482754  [INFO] Starting NGINX...
2024-06-05T08:45:59.201784292+02:00 2024-06-05 06:45:59.201708679  [INFO] Removing stale config from last run...
2024-06-05T08:45:59.202581392+02:00 2024-06-05 06:45:59.202549935  [INFO] Preparing new go2rtc config...
2024-06-05T08:45:59.202738921+02:00 s6-rc: info: service legacy-services successfully started
2024-06-05T08:45:59.207947297+02:00 2024-06-05 06:45:59.207860812  [INFO] Starting Frigate...
2024-06-05T08:45:59.439277117+02:00 2024-06-05 06:45:59.439108556  [INFO] Not injecting WebRTC candidates into go2rtc config as it has been set manually
2024-06-05T08:45:59.488186151+02:00 2024-06-05 06:45:59.488041476  [INFO] Starting go2rtc...
2024-06-05T08:45:59.617027246+02:00 2024-06-05 06:45:59.616919187  06:45:59.616 INF go2rtc version 1.8.4 linux/amd64
2024-06-05T08:45:59.617401645+02:00 2024-06-05 06:45:59.617374036  06:45:59.617 INF [rtsp] listen addr=:8554
2024-06-05T08:45:59.617427472+02:00 2024-06-05 06:45:59.617409095  06:45:59.617 INF [api] listen addr=:1984
2024-06-05T08:45:59.618311337+02:00 2024-06-05 06:45:59.618249477  06:45:59.618 INF [webrtc] listen addr=:8555
2024-06-05T08:46:00.668662179+02:00 2024-06-05 06:46:00.668584690  [2024-06-05 06:46:00] frigate.app                    INFO    : Starting Frigate (0.13.2-6476f8a)
2024-06-05T08:46:00.723312310+02:00 2024-06-05 06:46:00.723201844  [2024-06-05 06:46:00] peewee_migrate.logs            INFO    : Starting migrations
2024-06-05T08:46:00.727296405+02:00 2024-06-05 06:46:00.727186914  [2024-06-05 06:46:00] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-06-05T08:46:00.732590480+02:00 2024-06-05 06:46:00.732438193  [2024-06-05 06:46:00] frigate.app                    INFO    : Recording process started: 594
2024-06-05T08:46:00.734645803+02:00 2024-06-05 06:46:00.734533892  [2024-06-05 06:46:00] frigate.app                    INFO    : go2rtc process pid: 95
2024-06-05T08:46:00.741489371+02:00 2024-06-05 06:46:00.741432104  [2024-06-05 06:46:00] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for parkplatz. Keeping the 6 most recent segments out of 7 and discarding the rest...
2024-06-05T08:46:00.755782013+02:00 2024-06-05 06:46:00.755735347  [2024-06-05 06:46:00] detector.coral                 INFO    : Starting detection process: 604
2024-06-05T08:46:00.759237256+02:00 2024-06-05 06:46:00.759171071  [2024-06-05 06:46:00] frigate.app                    INFO    : Output process started: 606
2024-06-05T08:46:00.766872333+02:00 2024-06-05 06:46:00.766787080  [2024-06-05 06:46:00] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2024-06-05T08:46:00.767019100+02:00 2024-06-05 06:46:00.766966302  Process detector:coral:
2024-06-05T08:46:00.767061012+02:00 2024-06-05 06:46:00.767023553  [2024-06-05 06:46:00] frigate.detectors.plugins.edgetpu_tfl ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
2024-06-05T08:46:00.768015620+02:00 2024-06-05 06:46:00.767971000  Traceback (most recent call last):
2024-06-05T08:46:00.768036625+02:00 2024-06-05 06:46:00.767983041    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
2024-06-05T08:46:00.768042816+02:00 2024-06-05 06:46:00.767984414      delegate = Delegate(library, options)
2024-06-05T08:46:00.768048093+02:00 2024-06-05 06:46:00.767985935    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__
2024-06-05T08:46:00.768063061+02:00 2024-06-05 06:46:00.767991237      raise ValueError(capture.message)
2024-06-05T08:46:00.768074983+02:00 2024-06-05 06:46:00.768004816  ValueError
2024-06-05T08:46:00.768080965+02:00 2024-06-05 06:46:00.768005950  
2024-06-05T08:46:00.768086068+02:00 2024-06-05 06:46:00.768007379  During handling of the above exception, another exception occurred:
2024-06-05T08:46:00.768097402+02:00 2024-06-05 06:46:00.768008472  
2024-06-05T08:46:00.768102690+02:00 2024-06-05 06:46:00.768009791  Traceback (most recent call last):
2024-06-05T08:46:00.768110223+02:00 2024-06-05 06:46:00.768030232    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2024-06-05T08:46:00.768115597+02:00 2024-06-05 06:46:00.768031537      self.run()
2024-06-05T08:46:00.768120408+02:00 2024-06-05 06:46:00.768033102    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2024-06-05T08:46:00.768129527+02:00 2024-06-05 06:46:00.768034453      self._target(*self._args, **self._kwargs)
2024-06-05T08:46:00.768138855+02:00 2024-06-05 06:46:00.768045065    File "/opt/frigate/frigate/object_detection.py", line 102, in run_detector
2024-06-05T08:46:00.768144361+02:00 2024-06-05 06:46:00.768046474      object_detector = LocalObjectDetector(detector_config=detector_config)
2024-06-05T08:46:00.768153215+02:00 2024-06-05 06:46:00.768047897    File "/opt/frigate/frigate/object_detection.py", line 53, in __init__
2024-06-05T08:46:00.768158923+02:00 2024-06-05 06:46:00.768049352      self.detect_api = create_detector(detector_config)
2024-06-05T08:46:00.768163708+02:00 2024-06-05 06:46:00.768050805    File "/opt/frigate/frigate/detectors/__init__.py", line 18, in create_detector
2024-06-05T08:46:00.768168540+02:00 2024-06-05 06:46:00.768071367      return api(detector_config)
2024-06-05T08:46:00.768177224+02:00 2024-06-05 06:46:00.768073189    File "/opt/frigate/frigate/detectors/plugins/edgetpu_tfl.py", line 41, in __init__
2024-06-05T08:46:00.768182350+02:00 2024-06-05 06:46:00.768075795      edge_tpu_delegate = load_delegate("libedgetpu.so.1.0", device_config)
2024-06-05T08:46:00.768187042+02:00 2024-06-05 06:46:00.768077681    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 162, in load_delegate
2024-06-05T08:46:00.768196224+02:00 2024-06-05 06:46:00.768101660      raise ValueError('Failed to load delegate from {}\n{}'.format(
2024-06-05T08:46:00.768201323+02:00 2024-06-05 06:46:00.768112116  ValueError: Failed to load delegate from libedgetpu.so.1.0
2024-06-05T08:46:00.768206092+02:00 2024-06-05 06:46:00.768113487  
2024-06-05T08:46:00.773904868+02:00 2024-06-05 06:46:00.773799423  [2024-06-05 06:46:00] frigate.app                    INFO    : Camera processor started for eingang: 613
2024-06-05T08:46:00.779496589+02:00 2024-06-05 06:46:00.779377354  [2024-06-05 06:46:00] frigate.app                    INFO    : Camera processor started for fassade_nord: 615
2024-06-05T08:46:00.786879510+02:00 2024-06-05 06:46:00.786777991  [2024-06-05 06:46:00] frigate.app                    INFO    : Camera processor started for fassade_sued: 625
2024-06-05T08:46:00.792431955+02:00 2024-06-05 06:46:00.792349039  [2024-06-05 06:46:00] frigate.app                    INFO    : Camera processor started for parkplatz: 632
2024-06-05T08:46:00.797497914+02:00 2024-06-05 06:46:00.797407282  [2024-06-05 06:46:00] frigate.app                    INFO    : Capture process started for eingang: 634
2024-06-05T08:46:00.802815216+02:00 2024-06-05 06:46:00.802720061  [2024-06-05 06:46:00] frigate.app                    INFO    : Capture process started for fassade_nord: 639
2024-06-05T08:46:00.808545864+02:00 2024-06-05 06:46:00.808438746  [2024-06-05 06:46:00] frigate.app                    INFO    : Capture process started for fassade_sued: 644
2024-06-05T08:46:00.817898023+02:00 2024-06-05 06:46:00.817789584  [2024-06-05 06:46:00] frigate.app                    INFO    : Capture process started for parkplatz: 661
2024-06-05T08:46:04.006212213+02:00 2024-06-05 06:46:04.006079560  [2024-06-05 06:46:04] frigate.video                  ERROR   : eingang: Unable to read frames from ffmpeg process.
2024-06-05T08:46:04.006565624+02:00 2024-06-05 06:46:04.006517670  [2024-06-05 06:46:04] frigate.video                  ERROR   : eingang: Unable to read frames from ffmpeg process.
2024-06-05T08:46:04.006887560+02:00 2024-06-05 06:46:04.006845152  [2024-06-05 06:46:04] frigate.video                  ERROR   : eingang: Unable to read frames from ffmpeg process.
2024-06-05T08:46:04.007250925+02:00 2024-06-05 06:46:04.007204928  [2024-06-05 06:46:04] frigate.video                  ERROR   : eingang: Unable to read frames from ffmpeg process.
2024-06-05T08:46:04.007649864+02:00 2024-06-05 06:46:04.007611300  [2024-06-05 06:46:04] frigate.video                  ERROR   : eingang: Unable to read frames from ffmpeg process.
2024-06-05T08:46:04.008112908+02:00 2024-06-05 06:46:04.008062419  [2024-06-05 06:46:04] frigate.video                  ERROR   : eingang: Unable to read frames from ffmpeg process.
2024-06-05T08:46:04.008409072+02:00 2024-06-05 06:46:04.008360064  [2024-06-05 06:46:04] frigate.video                  ERROR   : eingang: Unable to read frames from ffmpeg process.
2024-06-05T08:46:04.008740271+02:00 2024-06-05 06:46:04.008705561  [2024-06-05 06:46:04] frigate.video                  ERROR   : eingang: Unable to read frames from ffmpeg process.
2024-06-05T08:46:04.009081382+02:00 2024-06-05 06:46:04.009038546  [2024-06-05 06:46:04] frigate.video                  ERROR   : eingang: Unable to read frames from ffmpeg process.
2024-06-05T08:46:04.009643895+02:00 2024-06-05 06:46:04.009607710  [2024-06-05 06:46:04] frigate.video                  ERROR   : eingang: Unable to read frames from ffmpeg process.
2024-06-05T08:46:04.009897327+02:00 2024-06-05 06:46:04.009857837  [2024-06-05 06:46:04] frigate.video                  ERROR   : eingang: Unable to read frames from ffmpeg process.
2024-06-05T08:46:04.010242282+02:00 2024-06-05 06:46:04.010211537  [2024-06-05 06:46:04] frigate.video                  ERROR   : eingang: Unable to read frames from ffmpeg process.
2024-06-05T08:46:04.010588183+02:00 2024-06-05 06:46:04.010560530  [2024-06-05 06:46:04] frigate.video                  ERROR   : eingang: Unable to read frames from ffmpeg process.
2024-06-05T08:46:04.010988825+02:00 2024-06-05 06:46:04.010930184  [2024-06-05 06:46:04] frigate.video                  ERROR   : eingang: Unable to read frames from ffmpeg process.
2024-06-05T08:46:04.011285287+02:00 2024-06-05 06:46:04.011244121  [2024-06-05 06:46:04] frigate.video                  ERROR   : eingang: Unable to read frames from ffmpeg process.
2024-06-05T08:46:04.011678682+02:00 2024-06-05 06:46:04.011603858  [2024-06-05 06:46:04] frigate.video                  ERROR   : eingang: Unable to read frames from ffmpeg process.
2024-06-05T08:46:04.011961718+02:00 2024-06-05 06:46:04.011932783  [2024-06-05 06:46:04] frigate.video                  ERROR   : eingang: Unable to read frames from ffmpeg process.
2024-06-05T08:46:04.012300031+02:00 2024-06-05 06:46:04.012269257  [2024-06-05 06:46:04] frigate.video                  ERROR   : eingang: Unable to read frames from ffmpeg process.
2024-06-05T08:46:04.012614542+02:00 2024-06-05 06:46:04.012584517  [2024-06-05 06:46:04] frigate.video                  ERROR   : eingang: Unable to read frames from ffmpeg process.
2024-06-05T08:46:04.052205628+02:00 2024-06-05 06:46:04.052135864  [2024-06-05 06:46:04] frigate.video                  ERROR   : eingang: Unable to read frames from ffmpeg process.
2024-06-05T08:46:04.052438476+02:00 2024-06-05 06:46:04.052388794  [2024-06-05 06:46:04] frigate.video                  ERROR   : eingang: ffmpeg process is not running. exiting capture thread...
2024-06-05T08:46:09.200010578+02:00 2024-06-05 06:46:09.199864752  [INFO] Starting go2rtc healthcheck service...
2024-06-05T08:46:09.828146790+02:00 2024-06-05 06:46:09.828060835  192.168.1.151 - - [05/Jun/2024:06:46:09 +0000] "GET /api HTTP/1.1" 301 169 "-" "kube-probe/1.26" "-"
2024-06-05T08:46:09.830879348+02:00 2024-06-05 06:46:09.830802853  192.168.1.151 - - [05/Jun/2024:06:46:09 +0000] "GET /api/ HTTP/1.1" 200 38 "http://192.168.1.151:5000/api" "kube-probe/1.26" "-"
2024-06-05T08:46:09.831683696+02:00 2024-06-05 06:46:09.831620650  192.168.1.151 - - [05/Jun/2024:06:46:09 +0000] "GET /api HTTP/1.1" 301 169 "-" "kube-probe/1.26" "-"
2024-06-05T08:46:09.833513004+02:00 2024-06-05 06:46:09.833468684  192.168.1.151 - - [05/Jun/2024:06:46:09 +0000] "GET /api/ HTTP/1.1" 200 38 "http://192.168.1.151:5000/api" "kube-probe/1.26" "-"
2024-06-05T08:46:14.827673787+02:00 2024-06-05 06:46:14.827480248  192.168.1.151 - - [05/Jun/2024:06:46:14 +0000] "GET /api HTTP/1.1" 301 169 "-" "kube-probe/1.26" "-"
2024-06-05T08:46:14.827808006+02:00 2024-06-05 06:46:14.827561015  192.168.1.151 - - [05/Jun/2024:06:46:14 +0000] "GET /api HTTP/1.1" 301 169 "-" "kube-probe/1.26" "-"
2024-06-05T08:46:14.831329260+02:00 2024-06-05 06:46:14.831184682  192.168.1.151 - - [05/Jun/2024:06:46:14 +0000] "GET /api/ HTTP/1.1" 200 38 "http://192.168.1.151:5000/api" "kube-probe/1.26" "-"
2024-06-05T08:46:15.330488733+02:00 2024-06-05 06:46:15.330411675  192.168.1.151 - - [05/Jun/2024:06:46:15 +0000] "GET /api/ HTTP/1.1" 200 38 "http://192.168.1.151:5000/api" "kube-probe/1.26" "-"
2024-06-05T08:46:15.743492807+02:00 2024-06-05 06:46:15.743403761  [2024-06-05 06:46:15] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for parkplatz. Keeping the 6 most recent segments out of 7 and discarding the rest...
2024-06-05T08:46:20.824202665+02:00 2024-06-05 06:46:20.824070580  [2024-06-05 06:46:20] watchdog.eingang               ERROR   : Ffmpeg process crashed unexpectedly for eingang.
2024-06-05T08:46:20.824348419+02:00 2024-06-05 06:46:20.824255847  [2024-06-05 06:46:20] watchdog.eingang               ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2024-06-05T08:46:20.824468483+02:00 2024-06-05 06:46:20.824383260  [2024-06-05 06:46:20] ffmpeg.eingang.detect          ERROR   : [h264 @ 0x55c4f455c040] non-existing PPS 37 referenced
2024-06-05T08:46:20.824590274+02:00 2024-06-05 06:46:20.824532904  [2024-06-05 06:46:20] ffmpeg.eingang.detect          ERROR   : [extract_extradata @ 0x55c4f45ac300] Invalid NAL unit 0, skipping.
2024-06-05T08:46:20.824734293+02:00 2024-06-05 06:46:20.824669570  [2024-06-05 06:46:20] ffmpeg.eingang.detect          ERROR   :     Last message repeated 3 times
2024-06-05T08:46:20.824983569+02:00 2024-06-05 06:46:20.824912491  [2024-06-05 06:46:20] ffmpeg.eingang.detect          ERROR   : [h264 @ 0x55c4f455c040] Invalid NAL unit 0, skipping.
2024-06-05T08:46:20.825118996+02:00 2024-06-05 06:46:20.825078848  [2024-06-05 06:46:20] ffmpeg.eingang.detect          ERROR   :     Last message repeated 3 times
2024-06-05T08:46:20.825271508+02:00 2024-06-05 06:46:20.825238066  [2024-06-05 06:46:20] ffmpeg.eingang.detect          ERROR   : [h264 @ 0x55c4f455c040] data partitioning is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.
2024-06-05T08:46:20.825396914+02:00 2024-06-05 06:46:20.825359931  [2024-06-05 06:46:20] ffmpeg.eingang.detect          ERROR   : [h264 @ 0x55c4f455c040] If you want to help, upload a sample of this file to https://streams.videolan.org/upload/ and contact the ffmpeg-devel mailing list. (ffmpeg-devel@ffmpeg.org)
2024-06-05T08:46:20.825508793+02:00 2024-06-05 06:46:20.825477887  [2024-06-05 06:46:20] ffmpeg.eingang.detect          ERROR   : [h264 @ 0x55c4f455c040] data partitioning is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.
2024-06-05T08:46:20.825620825+02:00 2024-06-05 06:46:20.825588870  [2024-06-05 06:46:20] ffmpeg.eingang.detect          ERROR   : [h264 @ 0x55c4f455c040] If you want to help, upload a sample of this file to https://streams.videolan.org/upload/ and contact the ffmpeg-devel mailing list. (ffmpeg-devel@ffmpeg.org)
2024-06-05T08:46:20.825729085+02:00 2024-06-05 06:46:20.825694955  [2024-06-05 06:46:20] ffmpeg.eingang.detect          ERROR   : [h264 @ 0x55c4f455c040] no frame!
2024-06-05T08:46:20.825840529+02:00 2024-06-05 06:46:20.825806677  [2024-06-05 06:46:20] ffmpeg.eingang.detect          ERROR   : [rtsp @ 0x55c4f4557140] Stream #0: not enough frames to estimate rate; consider increasing probesize
2024-06-05T08:46:20.825945869+02:00 2024-06-05 06:46:20.825914806  [2024-06-05 06:46:20] ffmpeg.eingang.detect          ERROR   : [rtsp @ 0x55c4f4557140] Could not find codec parameters for stream 0 (Video: h264, none): unspecified size
2024-06-05T08:46:20.826060297+02:00 2024-06-05 06:46:20.826029208  [2024-06-05 06:46:20] ffmpeg.eingang.detect          ERROR   : Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
2024-06-05T08:46:20.826172169+02:00 2024-06-05 06:46:20.826138393  [2024-06-05 06:46:20] ffmpeg.eingang.detect          ERROR   : [segment @ 0x55c4f456e4c0] dimensions not set
2024-06-05T08:46:20.826280954+02:00 2024-06-05 06:46:20.826245945  [2024-06-05 06:46:20] ffmpeg.eingang.detect          ERROR   : Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
2024-06-05T08:46:20.826385528+02:00 2024-06-05 06:46:20.826354352  [2024-06-05 06:46:20] ffmpeg.eingang.detect          ERROR   : Error initializing output stream 0:0 -- 
2024-06-05T08:46:20.826496552+02:00 2024-06-05 06:46:20.826465201  [2024-06-05 06:46:20] ffmpeg.eingang.detect          ERROR   : 
2024-06-05T08:46:20.928635599+02:00 2024-06-05 06:46:20.928492020  [2024-06-05 06:46:20] frigate.watchdog               INFO    : Detection appears to have stopped. Exiting Frigate...
2024-06-05T08:46:20.932924097+02:00 s6-rc: info: service legacy-services: stopping
2024-06-05T08:46:20.936388681+02:00 s6-rc: info: service legacy-services successfully stopped
2024-06-05T08:46:20.936455816+02:00 s6-rc: info: service nginx: stopping
2024-06-05T08:46:20.936747403+02:00 s6-rc: info: service go2rtc-healthcheck: stopping
2024-06-05T08:46:20.944248181+02:00 2024-06-05 06:46:20.944168380  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
2024-06-05T08:46:20.944791562+02:00 s6-rc: info: service go2rtc-healthcheck successfully stopped
2024-06-05T08:46:21.023179053+02:00 2024-06-05 06:46:21.023091771  [INFO] Service NGINX exited with code 0 (by signal 0)
2024-06-05T08:46:21.023900006+02:00 s6-rc: info: service nginx successfully stopped
2024-06-05T08:46:21.023936046+02:00 s6-rc: info: service nginx-log: stopping
2024-06-05T08:46:21.024093728+02:00 s6-rc: info: service frigate: stopping
2024-06-05T08:46:21.025561917+02:00 2024-06-05 06:46:21.025500068  [2024-06-05 06:46:21] frigate.app                    INFO    : Stopping...
2024-06-05T08:46:21.026287196+02:00 s6-rc: info: service nginx-log successfully stopped
2024-06-05T08:46:21.028633007+02:00 2024-06-05 06:46:21.028497785  [2024-06-05 06:46:21] frigate.stats                  INFO    : Exiting stats emitter...
2024-06-05T08:46:21.028892972+02:00 2024-06-05 06:46:21.028819630  [2024-06-05 06:46:21] frigate.storage                INFO    : Exiting storage maintainer...
2024-06-05T08:46:21.029018055+02:00 2024-06-05 06:46:21.028970455  [2024-06-05 06:46:21] frigate.events.cleanup         INFO    : Exiting event cleanup...
2024-06-05T08:46:21.030307523+02:00 2024-06-05 06:46:21.029527749  [2024-06-05 06:46:21] frigate.ptz.autotrack          INFO    : Exiting autotracker...
2024-06-05T08:46:21.030352784+02:00 2024-06-05 06:46:21.029684486  [2024-06-05 06:46:21] frigate.record.cleanup         INFO    : Exiting recording cleanup...
2024-06-05T08:46:21.030406875+02:00 2024-06-05 06:46:21.029873514  [2024-06-05 06:46:21] frigate.watchdog               INFO    : Exiting watchdog...
2024-06-05T08:46:21.048013740+02:00 2024-06-05 06:46:21.047918071  [2024-06-05 06:46:21] frigate.object_processing      INFO    : Exiting object processor...
2024-06-05T08:46:21.260660461+02:00 2024-06-05 06:46:21.260526871  [2024-06-05 06:46:21] frigate.comms.ws               INFO    : Exiting websocket client...
2024-06-05T08:46:21.938632295+02:00 2024-06-05 06:46:21.938565634  [2024-06-05 06:46:21] frigate.events.maintainer      INFO    : Exiting event processor...
2024-06-05T08:46:21.938744590+02:00 2024-06-05 06:46:21.938697387  [2024-06-05 06:46:21] peewee.sqliteq                 INFO    : writer received shutdown request, exiting.
2024-06-05T08:46:21.940607552+02:00 2024-06-05 06:46:21.940547770  [2024-06-05 06:46:21] watchdog.fassade_sued          INFO    : Terminating the existing ffmpeg process...
2024-06-05T08:46:21.941889739+02:00 2024-06-05 06:46:21.941841284  [2024-06-05 06:46:21] watchdog.fassade_nord          INFO    : Terminating the existing ffmpeg process...
2024-06-05T08:46:21.941968525+02:00 2024-06-05 06:46:21.941939248  [2024-06-05 06:46:21] watchdog.fassade_sued          INFO    : Waiting for ffmpeg to exit gracefully...
2024-06-05T08:46:21.942078302+02:00 2024-06-05 06:46:21.942029942  [2024-06-05 06:46:21] watchdog.eingang               INFO    : Terminating the existing ffmpeg process...
2024-06-05T08:46:21.942139186+02:00 2024-06-05 06:46:21.942113721  [2024-06-05 06:46:21] watchdog.parkplatz             INFO    : Terminating the existing ffmpeg process...
2024-06-05T08:46:21.942206305+02:00 2024-06-05 06:46:21.942183330  [2024-06-05 06:46:21] watchdog.fassade_nord          INFO    : Waiting for ffmpeg to exit gracefully...
2024-06-05T08:46:21.942276451+02:00 2024-06-05 06:46:21.942252608  [2024-06-05 06:46:21] watchdog.parkplatz             INFO    : Waiting for ffmpeg to exit gracefully...
2024-06-05T08:46:21.942348277+02:00 2024-06-05 06:46:21.942320307  [2024-06-05 06:46:21] watchdog.eingang               INFO    : Waiting for ffmpeg to exit gracefully...
2024-06-05T08:46:22.801752070+02:00 2024-06-05 06:46:22.801590943  [2024-06-05 06:46:22] frigate.video                  INFO    : eingang: exiting subprocess
2024-06-05T08:46:23.331946414+02:00 2024-06-05 06:46:23.331760587  [2024-06-05 06:46:23] frigate.output                 INFO    : exiting output process...
2024-06-05T08:46:26.292557328+02:00 2024-06-05 06:46:26.292456585  /usr/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 34 leaked shared_memory objects to clean up at shutdown
2024-06-05T08:46:26.292606443+02:00 2024-06-05 06:46:26.292460750    warnings.warn('resource_tracker: There appear to be %d '
2024-06-05T08:46:26.295567959+02:00 2024-06-05 06:46:26.295517886  [INFO] Service Frigate exited with code 0 (by signal 0)
2024-06-05T08:46:26.296732191+02:00 s6-rc: info: service frigate successfully stopped
2024-06-05T08:46:26.296832454+02:00 s6-rc: info: service go2rtc: stopping
2024-06-05T08:46:26.296933234+02:00 s6-rc: info: service frigate-log: stopping
2024-06-05T08:46:26.297897800+02:00 2024-06-05 06:46:26.297708030  exit with signal: terminated
2024-06-05T08:46:26.298976650+02:00 s6-rc: info: service frigate-log successfully stopped
2024-06-05T08:46:26.302025200+02:00 2024-06-05 06:46:26.301974228  [INFO] The go2rtc service exited with code 0 (by signal 0)
2024-06-05T08:46:26.302626847+02:00 s6-rc: info: service go2rtc successfully stopped
2024-06-05T08:46:26.302713939+02:00 s6-rc: info: service go2rtc-log: stopping
2024-06-05T08:46:26.304635939+02:00 s6-rc: info: service go2rtc-log successfully stopped
2024-06-05T08:46:26.304692705+02:00 s6-rc: info: service log-prepare: stopping
2024-06-05T08:46:26.304813825+02:00 s6-rc: info: service s6rc-fdholder: stopping
2024-06-05T08:46:26.305790073+02:00 s6-rc: info: service log-prepare successfully stopped
2024-06-05T08:46:26.305913450+02:00 s6-rc: info: service legacy-cont-init: stopping
2024-06-05T08:46:26.306671303+02:00 s6-rc: info: service s6rc-fdholder successfully stopped
2024-06-05T08:46:26.310176002+02:00 s6-rc: info: service legacy-cont-init successfully stopped
2024-06-05T08:46:26.310225021+02:00 s6-rc: info: service fix-attrs: stopping
2024-06-05T08:46:26.311142868+02:00 s6-rc: info: service fix-attrs successfully stopped
2024-06-05T08:46:26.311250442+02:00 s6-rc: info: service s6rc-oneshot-runner: stopping
2024-06-05T08:46:26.313044423+02:00 s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by Danit2** [comment]
Here are the config: 

detectors:
  coral:
    type: edgetpu
    device: usb

Yes it is the problem that the coral is stuck and can not be found. But why there comes to a liveness probe problem? 
When the gpu is not detectet there only a error  in frigate but the the liveness probe is not a problem.

**Comment by stavros-k** [comment]
Config looks fine to me
The liveness probe fails because frigate it self fails to start when it cannot detect the coral.
Even without any probes, frigate wouldn't start due to coral.

**Comment by Danit2** [comment]
Are you shure? When frigate starts i have for around 30sec the web ui. 
After this frigate starts with the shutdown.

**Comment by stavros-k** [comment]
> Are you shure? When frigate starts i have for around 30sec the web ui.

Yes, I tried just now, _just to be sure_.
With disabled probes, and frigate setup to use coral (even tho I dont have one).

Not only it would stop, but it would never restart afterwards.
