### ISSUE TITLE
Immich Issue!!

### ISSUE THREAD

**Issue by zahmed257** [truenas/charts#2558]
immich upload --recursive /mnt/smbshare/
Crawling for assets...
file:///usr/local/lib/node_modules/@immich/cli/dist/index.js:17823
    extensions: [...image, ...video]
                    ^

TypeError: image is not iterable
    at scan (file:///usr/local/lib/node_modules/@immich/cli/dist/index.js:17823:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async upload (file:///usr/local/lib/node_modules/@immich/cli/dist/index.js:17805:17)

Node.js v20.14.0

**Comment by stavros-k** [comment]
Hello, this looks like an issue with the immich cli tool. I'd suggest you to react to their support channels

**Comment by zahmed257** [comment]
Ok. Thank you.
