### ISSUE TITLE
Plex upgrade fails when GPU is allocated

### ISSUE THREAD

**Issue by tvanbolderen** [truenas/charts#272]
While upgrading Plex (`1.24.5.5173_1.6.12` -> `1.25.2.5319_1.6.15`) I get an error due to my App having a GPU reservation.

I think it might be because 1 GPU is already allocated and when I try to install a second instance of Plex it now shows 0 resources available. Which might be why the upgrade fails. Removing the Plex App and redeploying it fixes the issue as the GPU allocation was freed up.

Stack trace:
```
Error: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 409, in run
    await self.future
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 445, in __run_body
    rv = await self.method(*([self] + args))
  File "/usr/lib/python3/dist-packages/middlewared/schema.py", line 1269, in nf
    return await func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/middlewared/schema.py", line 1137, in nf
    res = await f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/middlewared/plugins/chart_releases_linux/upgrade.py", line 116, in upgrade
    await self.upgrade_chart_release(job, release, options)
  File "/usr/lib/python3/dist-packages/middlewared/plugins/chart_releases_linux/upgrade.py", line 266, in upgrade_chart_release
    config, context = await self.middleware.call(
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1324, in call
    return await self._call(
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1281, in _call
    return await methodobj(*prepared_call.args)
  File "/usr/lib/python3/dist-packages/middlewared/plugins/chart_releases_linux/chart_release.py", line 432, in normalise_and_validate_values
    dict_obj = await self.middleware.call(
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1324, in call
    return await self._call(
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1281, in _call
    return await methodobj(*prepared_call.args)
  File "/usr/lib/python3/dist-packages/middlewared/plugins/chart_releases_linux/validation.py", line 68, in validate_values
    verrors.check()
  File "/usr/lib/python3/dist-packages/middlewared/service_exception.py", line 62, in check
    raise self
middlewared.service_exception.ValidationErrors: [EINVAL] gpuConfiguration.gpu.intel.com/i915: Invalid choice: 1
```

**Comment by sonicaj** [comment]
Thank you @tvanbolderen for letting us know about it, however can you please create an issue at https://jira.ixsystems.com and kindly make sure to upload a debug of your system ( System Settings -> Advanced -> Save Debug ) - we can take it from there then ( btw it looks like you don't have gpu available anymore but the debug should tell us more ). Thanks!
