### ISSUE TITLE
Cannot upgrade Immich app, need to apply force

### ISSUE THREAD

**Issue by Giterd** [truenas/charts#2745]
Version:  Dragonfish-24.04.2
Name:  immich
App Version:  1.111.0_4.0.10
Chart Version:  4.0.10

I recently set up a Truenas Scale system for the first time. I installed the Immich app and have it running nicely.  Yesterday I noticed that an upgrade to 1.112.1_4.0.12 is available and tried to install it.  However, the upgrade fails with the message "...App_Data/Immich/thumbs: path contains existing data and `force` was not specified".  Same for the uploads and videos paths.  Nginix app updated with no problem.

I am a newbie to Truenas, Charts and Immich - what am I missing, before I cross-post to the Immich app github?  How do I force?

More info:
Error: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 469, in run
    await self.future
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 511, in __run_body
    rv = await self.method(*args)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/schema/processor.py", line 187, in nf
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/schema/processor.py", line 47, in nf
    res = await f(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/plugins/chart_releases_linux/upgrade.py", line 116, in upgrade
    await self.upgrade_chart_release(job, release, options)
  File "/usr/lib/python3/dist-packages/middlewared/plugins/chart_releases_linux/upgrade.py", line 267, in upgrade_chart_release
    config, context = await self.middleware.call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1564, in call
    return await self._call(
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1417, in _call
    return await methodobj(*prepared_call.args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/plugins/chart_releases_linux/chart_release.py", line 353, in normalise_and_validate_values
    dict_obj = await self.middleware.call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1564, in call
    return await self._call(
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1417, in _call
    return await methodobj(*prepared_call.args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/plugins/chart_releases_linux/validation.py", line 72, in validate_values
    verrors.check()
  File "/usr/lib/python3/dist-packages/middlewared/service_exception.py", line 70, in check
    raise self
middlewared.service_exception.ValidationErrors: [EINVAL] chart_release_create.immichStorage.thumbs.hostPathConfig.acl: /mnt/NAS/App_Data/Immich/thumbs: path contains existing data and `force` was not specified
[EINVAL] chart_release_create.immichStorage.uploads.hostPathConfig.acl: /mnt/NAS/App_Data/Immich/uploads: path contains existing data and `force` was not specified
[EINVAL] chart_release_create.immichStorage.video.hostPathConfig.acl: /mnt/NAS/App_Data/Immich/video: path contains existing data and `force` was not specified

**Comment by stavros-k** [comment]
Disable ACL for now, the issue iis fixed on the next release (Electric Eel 24.10) when it is released
