### ISSUE TITLE
Paperless-ngx: wrong entry name "Redis password"

### ISSUE THREAD

**Issue by Meth69** [truenas/charts#2921]
Hi, I'd like to report an error in the deployment settings for paperless-ngx.
There is a field called "Redis password" which in fact is not the redis password but the redis port. If you don't put the default port id in it (which is 6379) the container won't start and throw an error. The app will be "Running" but the paperless container will be "Exited".
Hopefully this can be fixed, in the meantime everything works correctly if you input 6379 as the Redis Password.
Thanks in advance.
Kind regards.

**Comment by stavros-k** [comment]
Please share more info, like logs and how did you come to that conclusion. 

I just tested and it installs fine using password for redis password field.

Thanks

**Comment by Meth69** [comment]
`2024-11-07 15:00:31.868364+00:00Paperless-ngx docker container starting...
2024-11-07 15:00:31.878153+00:00Creating directory scratch directory /tmp/paperless
2024-11-07 15:00:31.879983+00:00Adjusting permissions of paperless files. This may take a while.
2024-11-07 15:00:31.896727+00:00Waiting for PostgreSQL to start...
2024-11-07 15:00:31.949414+00:00Connected to PostgreSQL
2024-11-07 15:00:32.662102+00:00Waiting for Redis...
2024-11-07 15:00:32.662148+00:00Traceback (most recent call last):
2024-11-07 15:00:32.662180+00:00File "/sbin/wait-for-redis.py", line 24, in <module>
2024-11-07 15:00:32.662339+00:00with Redis.from_url(url=REDIS_URL) as client:
2024-11-07 15:00:32.662400+00:00^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-07 15:00:32.662414+00:00File "/usr/local/lib/python3.12/site-packages/redis/client.py", line 145, in from_url
2024-11-07 15:00:32.662618+00:00connection_pool = ConnectionPool.from_url(url, **kwargs)
2024-11-07 15:00:32.662679+00:00^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-07 15:00:32.662725+00:00File "/usr/local/lib/python3.12/site-packages/redis/connection.py", line 1274, in from_url
2024-11-07 15:00:32.663196+00:00url_options = parse_url(url)
2024-11-07 15:00:32.663219+00:00^^^^^^^^^^^^^^
2024-11-07 15:00:32.663233+00:00File "/usr/local/lib/python3.12/site-packages/redis/connection.py", line 1202, in parse_url
2024-11-07 15:00:32.663689+00:00if url.port:
2024-11-07 15:00:32.663710+00:00^^^^^^^^
2024-11-07 15:00:32.663719+00:00File "/usr/local/lib/python3.12/urllib/parse.py", line 182, in port
2024-11-07 15:00:32.663928+00:00raise ValueError(f"Port could not be cast to integer value as {port!r}")
2024-11-07 15:00:32.663968+00:00ValueError: Port could not be cast to integer value as '6O1mBXg^b*'
`

This is when using 6O1mBXg^b* as redis password.

**Comment by stavros-k** [comment]
I see, its not that its used as a port. But there is probably some character that is breaking the url parse in your password.
I'll URL encode the redis URL, which should fix this.

**Comment by Meth69** [comment]
You're right, the password was this one, i was wrong: 6O1mBXg^b*#1
And removing the # sign fixed the problem, so it's indeed what you're saying. Thanks for your help!
